branches:
  only:
  - master

env:
  global:
    - RGL_USE_NULL=TRUE

language: r
sudo: required
cache: packages
warnings_are_errors: true

addons:
  apt:
    packages:
      - libgit2-dev

r:
  - release

r_packages:
  - usethis
  - sessioninfo
  - data.table
  - downlit
  - delayed
  - origami
  - hal9001

r_github_packages:
  - rstudio/bslib
  - rstudio/bookdown
  - r-lib/sessioninfo
  #- tlverse/delayed@master
  #- tlverse/origami@master
  #- tlverse/hal9001@master
  - tlverse/sl3@devel
  - tlverse/tmle3@master
  - tlverse/tmle3mopttx@5ba5f65
  - tlverse/tmle3shift@master
  - nhejazi/haldensify@f0de4b5

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - travis_wait 80 ./_build.sh
  - test $TRAVIS_BRANCH = "master" && ./_deploy.sh

notifications:
  email:
    on_success: change
    on_failure: change
