branches:
  only:
  - master

env:
  global:
    - RGL_USE_NULL=TRUE

language: r
sudo: required
cache: packages
warnings_are_errors: true

addons:
  apt:
    packages:
      - libgit2-dev

r:
  - release

r_packages:
  - devtools
  - sessioninfo
  - data.table
  - downlit

r_github_packages:
  - rstudio/bslib
  - rstudio/bookdown
  - r-lib/sessioninfo
  - osofr/simcausal@master
  - osofr/condensier@master
  - nhejazi/haldensify@master
  - tlverse/hal9001@master
  - tlverse/delayed@master
  - tlverse/origami@master
  - tlverse/sl3@master
  - tlverse/tmle3@master
  - tlverse/tmle3mopttx@5ba5f65
  - tlverse/tmle3shift@master

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - test $TRAVIS_BRANCH = "master" && ./_deploy.sh

notifications:
  email:
    on_success: change
    on_failure: change
