language: r
cache: packages

r_packages:
  - devtools

r_github_packages:
  - tlverse/tlverse

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

after_success:
  - ./_build.sh
  - test $TRAVIS_BRANCH = "master" &&
    ./_deploy.sh
