language: r
cache: packages

r_packages:
  - devtools

r_github_packages:
  - tlverse/tlverse


before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh

