branches:
  only:
    - master

language: r
sudo: required
cran: http://cran.rstudio.com
latex: false
pandoc: true
warnings_are_errors: false
cache:
  directories:
  - "$HOME/.local/share/renv"
  - "$TRAVIS_BUILD_DIR/renv/library"
  - "$HOME/.TinyTeX/"

r:
  - release

apt_packages:
  - libgit2-dev
  - libxml2-dev
  - libssl-dev
  - libcurl4-openssl-dev

before_install:
  - sudo apt-get install -y texlive-extra-utils ghostscript

install:
  - cd .. && Rscript -e "install.packages(c('here', 'renv', 'tinytex'))"
  - Rscript -e "tinytex::install_tinytex()"
  - export PATH=$HOME/bin:${PATH}
  - Rscript -e "tinytex::tlmgr_install('enumitem')"
  - Rscript -e "tinytex::tlmgr_update()"
  - cd $TRAVIS_BUILD_DIR && Rscript -e "renv::restore()"

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - travis_wait 80 ./_build.sh
  - test $TRAVIS_BRANCH = "master" && ./_deploy.sh

notifications:
  email:
    on_success: change
    on_failure: change
