language: r
sudo: required
cache: packages
warnings_are_errors: true

r:
  - release
  - devel

before_install:
  - Rscript -e 'update.packages(ask = FALSE)'

r_packages:
  - devtools

r_github_packages:
  - tlverse/tlverse

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - test $TRAVIS_BRANCH = "master" &&
    ./_deploy.sh
